CATEGORIES = [
  "Arts: Design",
  "Arts: Fashion & Beauty",
  "Arts: Food",
  "Arts: Literature",
  "Arts: Performing Arts",
  "Arts: Visual Arts",
  "Business: Business New",
  "Business: Careers",
  "Business: Investing",
  "Business: Management & Marketing",
  "Business: Shopping",
  "Comedy",
  "Education: Education",
  "Education: Education Technology",
  "Education: Higher Education",
  "Education: K-12",
  "Education: Language Courses",
  "Education: Training",
  "Games & Hobbies: Automotive",
  "Games & Hobbies: Aviation",
  "Games & Hobbies: Hobbies",
  "Games & Hobbies: Other Games",
  "Games & Hobbies: Video Games",
  "Government & Organizations: Local",
  "Government & Organizations: National",
  "Government & Organizations: Non-Profit",
  "Government & Organizations: Regional",
  "Health: Alternative Health",
  "Health: Fitness & Nutrition",
  "Health: Self-Help",
  "Health: Sexuality",
  "Kids & Family",
  "Music",
  "News & Politics",
  "Religion & Spirituality: Buddhism",
  "Religion & Spirituality: Christianity",
  "Religion & Spirituality: Hinduism",
  "Religion & Spirituality: Islam",
  "Religion & Spirituality: Judaism",
  "Religion & Spirituality: Other",
  "Religion & Spirituality: Spirituality",
  "Science & Medicine: Medicine",
  "Science & Medicine: Natural Sciences",
  "Science & Medicine: Social Sciences",
  "Society & Culture: History",
  "Society & Culture: Personal Journals",
  "Society & Culture: Philosophy",
  "Society & Culture: Places & Travel",
  "Sports & Recreation: Amateur",
  "Sports & Recreation: College & High School",
  "Sports & Recreation: Outdoor",
  "Sports & Recreation: Professional",
  "Technology: Gadgets",
  "Technology: Tech News",
  "Technology: Podcasting",
  "Technology: Software How-To",
  "TV & Film"
]

LANGUAGES = [
  "Afrikaans [af]",
  "Albanian [sq]",
  "Basque [eu]",
  "Belarusian [be]",
  "Bulgarian [bg]",
  "Catalan [ca]",
  "Chinese (Simplified) [zh-cn]",
  "Chinese (Traditional) [zh-tw]",
  "Croatian [hr]",
  "Czech [cs]",
  "Danish [da]",
  "Dutch [nl]",
  "Dutch (Belgium) [nl-be]",
  "Dutch (Netherlands) [nl-nl]",
  "English [en]",
  "English (Australia) [en-au]",
  "English (Belize) [en-bz]",
  "English (Canada) [en-ca]",
  "English (Ireland) [en-ie]",
  "English (Jamaica) [en-jm]",
  "English (New Zealand) [en-nz]",
  "English (Phillipines) [en-ph]",
  "English (South Africa) [en-za]",
  "English (Trinidad) [en-tt]",
  "English (United Kingdom) [en-gb]",
  "English (United States) [en-us]",
  "English (Zimbabwe) [en-zw]",
  "Estonian [et]",
  "Faeroese [fo]",
  "Finnish [fi]",
  "French [fr]",
  "French (Belgium) [fr-be]",
  "French (Canada) [fr-ca]",
  "French (France) [fr-fr]",
  "French (Luxembourg) [fr-lu]",
  "French (Monaco) [fr-mc]",
  "French (Switzerland) [fr-ch]",
  "Galician [gl]",
  "Gaelic [gd]",
  "German [de]",
  "German (Austria) [de-at]",
  "German (Germany) [de-de]",
  "German (Liechtenstein) [de-li]",
  "German (Luxembourg) [de-lu]",
  "German (Switzerland) [de-ch]",
  "Greek [el]",
  "Hawaiian [haw]",
  "Hungarian [hu]",
  "Icelandic [is]",
  "Indonesian [in]",
  "Irish [ga]",
  "Italian [it]",
  "Italian (Italy) [it-it]",
  "Italian (Switzerland) [it-ch]",
  "Japanese   [ja]",
  "Korean [ko]",
  "Macedonian [mk]",
  "Norwegian [no]",
  "Polish [pl]",
  "Portuguese [pt]",
  "Portuguese (Brazil) [pt-br]",
  "Portuguese (Portugal) [pt-pt]",
  "Romanian [ro]",
  "Romanian (Moldova) [ro-mo]",
  "Romanian (Romania) [ro-ro]",
  "Russian [ru]",
  "Russian (Moldova) [ru-mo]",
  "Russian (Russia) [ru-ru]",
  "Serbian [sr]",
  "Slovak [sk]",
  "Slovenian [sl]",
  "Spanish [es]",
  "Spanish (Argentina) [es-ar]",
  "Spanish (Bolivia) [es-bo]",
  "Spanish (Chile) [es-cl]",
  "Spanish (Colombia) [es-co]",
  "Spanish (Costa Rica) [es-cr]",
  "Spanish (Dominican Republic) [es-do]",
  "Spanish (Ecuador) [es-ec]",
  "Spanish (El Salvador) [es-sv]",
  "Spanish (Guatemala) [es-gt]",
  "Spanish (Honduras) [es-hn]",
  "Spanish (Mexico) [es-mx]",
  "Spanish (Nicaragua) [es-ni]",
  "Spanish (Panama) [es-pa]",
  "Spanish (Paraguay) [es-py]",
  "Spanish (Peru) [es-pe]",
  "Spanish (Puerto Rico) [es-pr]",
  "Spanish (Spain) [es-es]",
  "Spanish (Uruguay) [es-uy]",
  "Spanish (Venezuela) [es-ve]",
  "Swedish [sv]",
  "Swedish (Finland) [sv-fi]",
  "Swedish (Sweden) [sv-se]",
  "Turkish [tr]",
  "Ukranian [uk]"
]

MEDIA_TYPES = [
  "mp4",
  "m4a",
  "mp3",
  "ogg",
  "opus"
]